services:
  db:
    image: postgres:16
    container_name: stg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stg
    ports:
      - "5432:5432"
    volumes:
      - stg_pgdata:/var/lib/postgresql/data

volumes:
  stg_pgdata: